### PR TITLE
fix: false schemas no longer crash the library

### LINKED ISSUE #143: Support false validation rules
#### Reason/Context
Currently, whenever types are simplified and come across a schema of type `false` it throws an error and the library won't generate anything which is far from ideal.

https://github.com/asyncapi/generator-model-sdk/blob/cc42b3ae7753044c173cbdd16cfa4f9fb7cb2c34/src/simplification/SimplifyTypes.ts#L16

#### Description
I suggest we just ignore that specific model entirely.

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR ensure false schemas are handled more gracefully.

**Related issues**
Fixes #143

### CODE REVIEW

File: src/simplification/Simplifier.ts [hunk 1]
```diff
@@ -38,6 +38,10 @@ export class Simplifier {
         return [cachedModel];
       }
     }
+    //If it is a false validation schema return no common model
+    if (typeof schema === 'boolean' && !schema) {
```
Comment (magicmatatjahu) [inline src/simplification/Simplifier.ts:42]:
```suggestion
    if (schema === false) {
```

**Review by magicmatatjahu — CHANGES_REQUESTED** [review]

**Review by magicmatatjahu — APPROVED** [review]
