### PR TITLE
fix: recursive schemas in AsyncAPI documents throw an error

### LINKED ISSUE #199: Recursive properties in AsyncAPI schema exceed stack size
#### Describe the bug
Given the following file (converted to JSON): https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml

Throws the following stacktrace: 
```
RangeError: Maximum call stack size exceeded
    at Schema.properties (/Users/lagoni/Documents/AsyncAPI/generator-model-sdk/node_modules/@asyncapi/parser/lib/models/schema.js:192:13)
    at Function.reflectSchemaNames (/Users/lagoni/Documents/AsyncAPI/generator-model-sdk/lib/processors/AsyncAPIInputProcessor.js:106:20)
    at /Users/lagoni/Documents/AsyncAPI/generator-model-sdk/lib/processors/AsyncAPIInputProcessor.js:109:54
    at Array.forEach (<anonymous>)
    at Function.reflectSchemaNames (/Users/lagoni/Documents/AsyncAPI/generator-model-sdk/lib/processors/AsyncAPIInputProcessor.js:108:49)
    at /Users/lagoni/Documents/AsyncAPI/generator-model-sdk/lib/processors/AsyncAPIInputProcessor.js:109:54
    at Array.forEach (<anonymous>)
    at Function.reflectSchemaNames (/Users/lagoni/Documents/AsyncAPI/generator-model-sdk/lib/processors/AsyncAPIInputProcessor.js:108:49)
    at /Users/lagoni/Documents/AsyncAPI/generator-model-sdk/lib/processors/AsyncAPIInputProcessor.js:109:54
    at Array.forEach (<anonymous>)
```

#### How to Reproduce
It is the [reflectSchemaNames](https://github.com/asyncapi/generator-model-sdk/blob/f47276c22db4c9e987a2f8e77b9ecdcee74aff54/src/processors/AsyncAPIInputProcessor.ts#L44) that does not handle circular properties.

#### Expected behavior
To handle recursive schemas

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR fixes the problem where recursive schemas in an AsyncAPI document throws stack size exceeding error.

**Related issue(s)**
fixes #199

### CODE REVIEW

File: src/processors/AsyncAPIInputProcessor.ts [hunk 1]
```diff
@@ -42,72 +43,81 @@ export class AsyncAPIInputProcessor extends AbstractInputProcessor {
...
+    alreadyIteratedSchemas: Map<string, Schema> = new Map()
   ): Schema | boolean {
     if (typeof schema === 'boolean') return schema;
+    const schemaUid = schema.uid();
+    if (alreadyIteratedSchemas.has(schemaUid)) {
+      const cachedOutputSchema = alreadyIteratedSchemas.get(schemaUid); 
+      if (cachedOutputSchema !== undefined) {
+        return cachedOutputSchema;
+      }
+    }
```
Comment (magicmatatjahu) [inline src/processors/AsyncAPIInputProcessor.ts:56]: If you call first `has` and then `get` you have sure that the key exists and also I don't think so that `cachedOutputSchema` can be undefined in some cases.

```suggestion
    if (alreadyIteratedSchemas.has(schemaUid)) {
      return alreadyIteratedSchemas.get(schemaUid); 
    }
```

**Review by magicmatatjahu — DISMISSED** [review]

**Comment by jonaslagoni** [comment]
@magicmatatjahu shouldnt we rename this function to `convertToSchema` instead of `reflectSchemaNames`? That is basically what it does

**Comment by magicmatatjahu** [comment]
@jonaslagoni Go ahead! :)

**Comment by jonaslagoni** [comment]
Code smell should be ignored.

**Review by magicmatatjahu — APPROVED** [review]

**Comment by jonaslagoni** [comment]
Thanks for the review 🙏
